name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-random-app:${{github.run_number}}
        context: .
      
    - name: Checkout gitops repo
      uses: actions/checkout@v2
      with:
        repository: vietchita/python-gitops
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops-repo

    - name: Update image in deployment.yaml
      run: |
        cd gitops-repo
        sed -i 's|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}/flask-random-app:${{github.run_number}}"'|g' deployment.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add deployment.yaml
        git commit -m "Update image tag to ${{ secrets.DOCKER_USERNAME }}/flask-random-app:${{github.run_number}}"
        git push
